[build]
publish = "book"
command = "curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.4/mdbook-v0.4.4-x86_64-unknown-linux-gnu.tar.gz | tar xvz && ./mdbook build"

[[redirects]]
from = "/*"
to = "/404.html"
status = 404
